#!/usr/bin/env python3
"""Generate six-face contact quadrature for the 0.01 x 0.01 x 0.02 m block."""

from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "constant" / "contactQuadrature"
CENTRE = (0.025, 0.025, 0.010)
HALF = (0.005, 0.005, 0.010)

# Three-point trapezoidal coordinates and normalized 1D weights. Their tensor
# product integrates a constant pressure to exactly the geometric face area.
XI = (-1.0, 0.0, 1.0)
W = (0.25, 0.50, 0.25)

points: list[tuple[float, float, float]] = []
normals: list[tuple[int, int, int]] = []
areas: list[float] = []


def add_face(axis: int, sign: int, tangential: tuple[int, int]) -> None:
    a, b = tangential
    face_area = (2.0 * HALF[a]) * (2.0 * HALF[b])
    for ia, qa in enumerate(XI):
        for ib, qb in enumerate(XI):
            local = [0.0, 0.0, 0.0]
            local[axis] = sign * HALF[axis]
            local[a] = qa * HALF[a]
            local[b] = qb * HALF[b]
            points.append(tuple(CENTRE[i] + local[i] for i in range(3)))
            normal = [0, 0, 0]
            normal[axis] = sign
            normals.append(tuple(normal))
            areas.append(face_area * W[ia] * W[ib])


add_face(0, -1, (1, 2))
add_face(0, +1, (1, 2))
add_face(1, -1, (0, 2))
add_face(1, +1, (0, 2))
add_face(2, -1, (0, 1))
add_face(2, +1, (0, 1))


def vector(value: tuple[float, float, float]) -> str:
    return "(" + " ".join(f"{component:.8g}" for component in value) + ")"


lines = ["// Generated by make_contact_quadrature.py; do not edit by hand."]
lines += ["contactPoints", "("]
lines += [f"    {vector(point)}" for point in points]
lines += [");", "", "contactNormals", "("]
lines += [f"    {vector(normal)}" for normal in normals]
lines += [");", "", "contactPointAreas", "("]
lines += [f"    {area:.12g}" for area in areas]
lines += [");", ""]
OUT.write_bytes("\n".join(lines).encode("ascii"))

print(f"Wrote {OUT}: {len(points)} oriented surface points")
print(f"Total surface quadrature area: {sum(areas):.6f} m2")
