#!/usr/bin/env python3
# 中文说明：生成 5 cm×5 cm×5 cm 水体的全域 1 mm 正交六面体网格字典。
"""Generate the deterministic uniform 1 mm OpenFOAM mesh.

The 50 x 50 x 50 Cartesian water mesh resolves the complete local domain at
1 mm, not only the cells near the iron block.  The Exner bed therefore has a
uniform 50 x 50 finite-area mesh.  Keeping one conformal block also removes
grading-interface truncation error from the quantitative 60 s baseline.
"""

from pathlib import Path

CASE = Path(__file__).resolve().parent
OUT = CASE / "system" / "blockMeshDict"

# Coordinates, cell counts and grading ratios (last cell / first cell).
# One 50 mm cube divided into 50 cells per axis gives exactly 1 mm everywhere.
X = [0.000, 0.050]
Y = [0.000, 0.050]
Z = [0.000, 0.050]
NX = [50]
NY = [50]
NZ = [50]
GX = [1.0]
GY = [1.0]
GZ = [1.0]


def vid(i: int, j: int, k: int) -> int:
    return k * len(X) * len(Y) + j * len(X) + i


def face(a: int, b: int, c: int, d: int) -> str:
    return f"            ({a} {b} {c} {d})"


lines = [
    "// 中文说明：定义 0.05 m×0.05 m×0.05 m 水体的全域 1 mm 正交六面体网格。",
    "FoamFile",
    "{",
    "    version 2.0;",
    "    format ascii;",
    "    class dictionary;",
    "    object blockMeshDict;",
    "}",
    "",
    "// Generated by make_variable_mesh.py. Do not edit this file by hand.",
    "scale 1;",
    "",
    "vertices",
    "(",
]

for z in Z:
    for y in Y:
        for x in X:
            lines.append(f"    ({x:.5f} {y:.5f} {z:.5f})")
lines += [");", "", "blocks", "("]

for k in range(len(NZ)):
    for j in range(len(NY)):
        for i in range(len(NX)):
            v000 = vid(i, j, k)
            v100 = vid(i + 1, j, k)
            v110 = vid(i + 1, j + 1, k)
            v010 = vid(i, j + 1, k)
            v001 = vid(i, j, k + 1)
            v101 = vid(i + 1, j, k + 1)
            v111 = vid(i + 1, j + 1, k + 1)
            v011 = vid(i, j + 1, k + 1)
            lines.append(
                "    hex "
                f"({v000} {v100} {v110} {v010} {v001} {v101} {v111} {v011}) "
                f"({NX[i]} {NY[j]} {NZ[k]}) "
                f"simpleGrading ({GX[i]} {GY[j]} {GZ[k]})"
            )
lines += [");", "", "edges ();", "", "boundary", "("]

patches: dict[str, tuple[str, list[str]]] = {
    "inlet": ("patch", []),
    "outlet": ("patch", []),
    "bed": ("wall", []),
    "top": ("symmetryPlane", []),
    "sideWalls": ("wall", []),
}

for k in range(len(NZ)):
    for j in range(len(NY)):
        # x = 0 and x = L
        patches["inlet"][1].append(
            face(vid(0, j, k), vid(0, j, k + 1),
                 vid(0, j + 1, k + 1), vid(0, j + 1, k))
        )
        i = len(NX)
        patches["outlet"][1].append(
            face(vid(i, j, k), vid(i, j + 1, k),
                 vid(i, j + 1, k + 1), vid(i, j, k + 1))
        )

for j in range(len(NY)):
    for i in range(len(NX)):
        # z = 0 and z = H
        patches["bed"][1].append(
            face(vid(i, j + 1, 0), vid(i + 1, j + 1, 0),
                 vid(i + 1, j, 0), vid(i, j, 0))
        )
        k = len(NZ)
        patches["top"][1].append(
            face(vid(i, j, k), vid(i + 1, j, k),
                 vid(i + 1, j + 1, k), vid(i, j + 1, k))
        )

for k in range(len(NZ)):
    for i in range(len(NX)):
        # y = 0 and y = W are grouped as sideWalls.
        patches["sideWalls"][1].append(
            face(vid(i, 0, k), vid(i + 1, 0, k),
                 vid(i + 1, 0, k + 1), vid(i, 0, k + 1))
        )
        j = len(NY)
        patches["sideWalls"][1].append(
            face(vid(i, j, k + 1), vid(i + 1, j, k + 1),
                 vid(i + 1, j, k), vid(i, j, k))
        )

for name, (kind, faces) in patches.items():
    lines += [f"    {name}", "    {", f"        type {kind};", "        faces", "        ("]
    lines.extend(faces)
    lines += ["        );", "    }"]

lines += [");", "", "mergePatchPairs ();", ""]
# Write bytes so Windows does not translate LF to CRLF.  The generated file is
# then byte-identical on Windows, Ubuntu and GitHub Actions.
OUT.write_bytes("\n".join(lines).encode("utf-8"))

ncells = sum(NX) * sum(NY) * sum(NZ)
nbed = sum(NX) * sum(NY)
print(f"Wrote {OUT}")
print(f"Nominal cells: {ncells:,}; finite-area bed faces: {nbed:,}")
