#!/usr/bin/env python3
"""Generate the annotated 1--25 mm multiblock OpenFOAM mesh.

The Cartesian topology is intentionally generated instead of hand-writing 75
blocks.  Every interface is conformal, which is required by the moving Exner
bed.  The 1 mm x/y core covers the 100 x 100 mm iron block plus 10 mm clearance
on every side.  The lowest 40 mm is also 1 mm in z; the remaining body height
uses 2 mm, and the free-surface cap grows to 10 mm.
"""

from pathlib import Path

CASE = Path(__file__).resolve().parent
OUT = CASE / "system" / "blockMeshDict"

# Coordinates, cell counts and grading ratios (last cell / first cell).
# The 0.10--0.19 m and 0.31--0.40 m bands smoothly connect the far field
# to the 1 mm core.  Maximum cells are the uniform 25 mm outer cells.
X = [0.00, 0.10, 0.19, 0.31, 0.40, 0.50]
Y = [0.00, 0.10, 0.19, 0.31, 0.40, 0.50]
Z = [0.00, 0.04, 0.22, 0.25]
NX = [4, 12, 120, 12, 4]
NY = [4, 12, 120, 12, 4]
NZ = [40, 90, 3]
GX = [1.0, 0.20, 1.0, 5.0, 1.0]
GY = [1.0, 0.20, 1.0, 5.0, 1.0]
GZ = [1.0, 1.0, 1.0]


def vid(i: int, j: int, k: int) -> int:
    return k * len(X) * len(Y) + j * len(X) + i


def face(a: int, b: int, c: int, d: int) -> str:
    return f"            ({a} {b} {c} {d})"


lines = [
    "FoamFile",
    "{",
    "    version 2.0;",
    "    format ascii;",
    "    class dictionary;",
    "    object blockMeshDict;",
    "}",
    "",
    "// Generated by make_variable_mesh.py. Do not edit this file by hand.",
    "scale 1;",
    "",
    "vertices",
    "(",
]

for z in Z:
    for y in Y:
        for x in X:
            lines.append(f"    ({x:.5f} {y:.5f} {z:.5f})")
lines += [");", "", "blocks", "("]

for k in range(len(NZ)):
    for j in range(len(NY)):
        for i in range(len(NX)):
            v000 = vid(i, j, k)
            v100 = vid(i + 1, j, k)
            v110 = vid(i + 1, j + 1, k)
            v010 = vid(i, j + 1, k)
            v001 = vid(i, j, k + 1)
            v101 = vid(i + 1, j, k + 1)
            v111 = vid(i + 1, j + 1, k + 1)
            v011 = vid(i, j + 1, k + 1)
            lines.append(
                "    hex "
                f"({v000} {v100} {v110} {v010} {v001} {v101} {v111} {v011}) "
                f"({NX[i]} {NY[j]} {NZ[k]}) "
                f"simpleGrading ({GX[i]} {GY[j]} {GZ[k]})"
            )
lines += [");", "", "edges ();", "", "boundary", "("]

patches: dict[str, tuple[str, list[str]]] = {
    "inlet": ("patch", []),
    "outlet": ("patch", []),
    "bed": ("wall", []),
    "top": ("symmetryPlane", []),
    "sideWalls": ("wall", []),
}

for k in range(len(NZ)):
    for j in range(len(NY)):
        # x = 0 and x = L
        patches["inlet"][1].append(
            face(vid(0, j, k), vid(0, j, k + 1),
                 vid(0, j + 1, k + 1), vid(0, j + 1, k))
        )
        i = len(NX)
        patches["outlet"][1].append(
            face(vid(i, j, k), vid(i, j + 1, k),
                 vid(i, j + 1, k + 1), vid(i, j, k + 1))
        )

for j in range(len(NY)):
    for i in range(len(NX)):
        # z = 0 and z = H
        patches["bed"][1].append(
            face(vid(i, j + 1, 0), vid(i + 1, j + 1, 0),
                 vid(i + 1, j, 0), vid(i, j, 0))
        )
        k = len(NZ)
        patches["top"][1].append(
            face(vid(i, j, k), vid(i + 1, j, k),
                 vid(i + 1, j + 1, k), vid(i, j + 1, k))
        )

for k in range(len(NZ)):
    for i in range(len(NX)):
        # y = 0 and y = W are grouped as sideWalls.
        patches["sideWalls"][1].append(
            face(vid(i, 0, k), vid(i + 1, 0, k),
                 vid(i + 1, 0, k + 1), vid(i, 0, k + 1))
        )
        j = len(NY)
        patches["sideWalls"][1].append(
            face(vid(i, j, k + 1), vid(i + 1, j, k + 1),
                 vid(i + 1, j, k), vid(i, j, k))
        )

for name, (kind, faces) in patches.items():
    lines += [f"    {name}", "    {", f"        type {kind};", "        faces", "        ("]
    lines.extend(faces)
    lines += ["        );", "    }"]

lines += [");", "", "mergePatchPairs ();", ""]
# Write bytes so Windows does not translate LF to CRLF.  The generated file is
# then byte-identical on Windows, Ubuntu and GitHub Actions.
OUT.write_bytes("\n".join(lines).encode("ascii"))

ncells = sum(NX) * sum(NY) * sum(NZ)
nbed = sum(NX) * sum(NY)
print(f"Wrote {OUT}")
print(f"Nominal cells: {ncells:,}; finite-area bed faces: {nbed:,}")
