#!/usr/bin/env python3
"""Write a bed-aware hierarchical decomposition for any MPI rank count.

All partitions span the full water depth (nz=1), so every rank owns part of
the Exner bed.  This avoids the zero-bed partitions that a generic 3D Scotch
split can create and balances the finite-area work as well as the volume work.
"""

from pathlib import Path
import math
import sys


def horizontal_factors(nproc: int) -> tuple[int, int]:
    """Return the closest-to-square integer factor pair nx >= ny."""
    ny = math.isqrt(nproc)
    while ny > 1 and nproc % ny:
        ny -= 1
    return nproc // ny, ny


if len(sys.argv) != 2:
    raise SystemExit("usage: set_decomposition.py NPROCS")

try:
    nprocs = int(sys.argv[1])
except ValueError as exc:
    raise SystemExit("NPROCS must be a positive integer") from exc
if nprocs < 1:
    raise SystemExit("NPROCS must be a positive integer")

nx, ny = horizontal_factors(nprocs)
target = Path(__file__).resolve().parent / "system" / "decomposeParDict"
content = f"""FoamFile
{{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      decomposeParDict;
}}

// Generated by set_decomposition.py. Every rank spans the full water depth.
numberOfSubdomains {nprocs};
method hierarchical;

hierarchicalCoeffs
{{
    n       ({nx} {ny} 1);
    delta   0.001;
    order   xyz;
}}
"""
target.write_bytes(content.encode("ascii"))
print(f"Wrote {target}: {nx} x {ny} x 1 = {nprocs} partitions")
